require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'

# Spec files often have long describe blocks
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

# Test support files can have longer methods
Metrics/MethodLength:
  Exclude:
    - 'spec/support/**/*'

# RSpec style configurations for skill documentation tests
RSpec/DescribeClass:
  Enabled: false  # Skills are markdown files, not classes

RSpec/MultipleExpectations:
  Max: 3  # Documentation tests often check multiple attributes

RSpec/ExampleLength:
  Max: 10  # Documentation tests can be longer

RSpec/NoExpectationExample:
  Enabled: false  # Some tests document expected behavior without assertions

RSpec/ContextWording:
  Enabled: false  # Allow descriptive context names

RSpec/AnyInstance:
  Enabled: false  # Mock infrastructure for Claude Code tools

RSpec/ExpectActual:
  Enabled: false  # Documentation tests use expect(true) for placeholders

RSpec/IdenticalEqualityAssertion:
  Enabled: false  # Documentation tests use placeholder assertions

RSpec/RepeatedExample:
  Enabled: false  # Documentation tests may have similar placeholder examples

# Buggy cop causing crashes
Capybara/RSpec/PredicateMatcher:
  Enabled: false
